// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data.Npgsql.DesignTime")>]
[<assembly: AssemblyProductAttribute("FSharp.Data.Npgsql")>]
[<assembly: AssemblyDescriptionAttribute("F# type providers to support statically typed access to input parameters and result set of sql statement in idiomatic F# way.")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.Npgsql.DesignTime"
    let [<Literal>] AssemblyProduct = "FSharp.Data.Npgsql"
    let [<Literal>] AssemblyDescription = "F# type providers to support statically typed access to input parameters and result set of sql statement in idiomatic F# way. Data modifications via statically typed tables."
    let [<Literal>] AssemblyVersion = "0.2.0"
    let [<Literal>] AssemblyFileVersion = "0.2.0"
